### ISSUE TITLE
Fix code scanning alert - Binding a socket to all network interfaces

### ISSUE THREAD

**Issue by fabriziosalmi** [fabriziosalmi/UglyFeed#21]
Tracking issue for:
- [ ] https://github.com/fabriziosalmi/UglyFeed/security/code-scanning/8

I workaround this just by using local address on docker like this:

`docker run -p 127.0.0.1:8001:8001 -p 127.0.0.1:8501:8501 --name uglyfeed --network uglyfeed fabriziosalmi/uglyfeed:latest`

I then tunnel both ports with cloudflared using different FQDNs like:
- `127.0.0.1:8501` mapped to `demo.uglyfeed.com` then I put a Cloudflare WAF rule to only allow my public ip address and I go to the UglyFeed UI via `https://demo.uglyfeed.com`
- `127.0.0.1:8001` mapped to `rss` and I access the generated XML using `https://xml.uglyfeed.com/uglyfeed.xml`

Same on docker-compose:

```
name: uglyfeed
services:
    uglyfeed:
        ports:
            - 127.0.0.1:8001:8001
            - 127.0.0.1:8501:8501
        container_name: uglyfeed
        networks:
            - uglyfeed
        image: fabriziosalmi/uglyfeed:latest
networks:
    uglyfeed:
        external: true
        name: uglyfeed
```

Note: your own domain or any free subdomain can be used instead of mine 👯‍♀️
