### ISSUE TITLE
Mounting local config files

### ISSUE THREAD

**Issue by d00vy** [fabriziosalmi/UglyFeed#23]
I was a bit confused by the Docker Compose instructions, since none of the adjustments I made to `config.yaml` or `feeds.txt` after cloning the repo made any difference. Mounting the files into the container worked for me and may be worth suggesting.

```yaml
name: uglyfeed
services:
    uglyfeed:
        ports:
            - 8001:8001
            - 8501:8501
        volumes:
            - ./config.yaml:/app/config.yaml
            - ./feeds.txt:/app/input/feeds.txt
        container_name: uglyfeed
        networks:
            - uglyfeed
        image: fabriziosalmi/uglyfeed:latest
networks:
    uglyfeed:
        external: true
        name: uglyfeed
```
