### ISSUE TITLE
Any website to RSS (for later processing)

### ISSUE THREAD

**Issue by fabriziosalmi** [fabriziosalmi/UglyFeed#28]
**Is your feature request related to a problem? Please describe.**

Convert any website to RSS (for later processing)

### Step 1: Create the Project Structure

1. Create a new GitHub repository.
2. Inside the repository, create the following directory structure:

```
.
├── .github
│   └── workflows
│       └── scrape_and_convert.yml
├── tools
│   ├── scrape_to_rdf.py
│   ├── rdf_to_rss.py
├── requirements.txt
```

### Step 2: Define Python Scripts

**`tools/scrape_to_rdf.py`**:

```python
import sys
import requests
from bs4 import BeautifulSoup
from rdflib import Graph, Literal, RDF, URIRef
from rdflib.namespace import FOAF, DC

def scrape_to_rdf(url, rdf_output_path):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    articles = soup.find_all('div', class_='article')
    data = []

    for article in articles:
        title = article.find('h2').text
        link = article.find('a')['href']
        description = article.find('p').text if article.find('p') else ''
        data.append({'title': title, 'link': link, 'description': description})

    g = Graph()
    EX = URIRef("http://example.org/")

    for item in data:
        article_uri = URIRef(item['link'])
        g.add((article_uri, RDF.type, FOAF.Document))
        g.add((article_uri, DC.title, Literal(item['title'])))
        g.add((article_uri, FOAF.homepage, URIRef(item['link'])))
        g.add((article_uri, DC.description, Literal(item['description'])))

    g.serialize(destination=rdf_output_path, format='turtle')

if __name__ == "__main__":
    scrape_to_rdf(sys.argv[1], sys.argv[2])
```

**`tools/rdf_to_rss.py`**:

```python
import sys
from rdflib import Graph, FOAF, DC
from lxml import etree

def rdf_to_rss(rdf_input_path, rss_output_path):
    g = Graph()
    g.parse(rdf_input_path, format="turtle")

    data = []
    for s, p, o in g:
        if p == DC.title:
            title = o
            link = [o2 for s2, p2, o2 in g.triples((s, FOAF.homepage, None))][0]
            description = [o3 for s3, p3, o3 in g.triples((s, DC.description, None))]
            description = description[0] if description else ''
            data.append({'title': title, 'link': link, 'description': description})

    rss = etree.Element("rss", version="2.0")
    channel = etree.SubElement(rss, "channel")

    etree.SubElement(channel, "title").text = "Example RSS Feed"
    etree.SubElement(channel, "link").text = "https://example.com"
    etree.SubElement(channel, "description").text = "This is an example RSS feed generated from RDF data."

    for item in data:
        item_element = etree.SubElement(channel, "item")
        etree.SubElement(item_element, "title").text = str(item['title'])
        etree.SubElement(item_element, "link").text = str(item['link'])
        etree.SubElement(item_element, "description").text = str(item['description'])

    rss_xml = etree.tostring(rss, pretty_print=True, xml_declaration=True, encoding="UTF-8")

    with open(rss_output_path, "wb") as f:
        f.write(rss_xml)

if __name__ == "__main__":
    rdf_to_rss(sys.argv[1], sys.argv[2])
```

### Step 3: Define Dependencies

**`requirements.txt`**:

```txt
rdflib
lxml
requests
beautifulsoup4
```

### Step 4: Create GitHub Action Workflow

**`.github/workflows/scrape_and_convert.yml`**:

```yaml
name: Scrape and Convert

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      website_url:
        description: 'The URL of the website to scrape'
        required: true
        default: 'https://example.com'
      rdf_output_path:
        description: 'Path to save the RDF output'
        required: true
        default: 'output/output.rdf'
      rss_output_path:
        description: 'Path to save the RSS output'
        required: true
        default: 'output/rss_feed.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Scrape website and generate RDF
      run: |
        python tools/scrape_to_rdf.py "${{ github.event.inputs.website_url }}" "${{ github.event.inputs.rdf_output_path }}"

    - name: Convert RDF to RSS
      run: |
        python tools/rdf_to_rss.py "${{ github.event.inputs.rdf_output_path }}" "${{ github.event.inputs.rss_output_path }}"

    - name: Upload RSS feed
      uses: actions/upload-artifact@v2
      with:
        name: rss-feed
        path: ${{ github.event.inputs.rss_output_path }}
```

### Summary

1. **Structure:** Place your Python scripts in the `tools` directory.
2. **Scripts:** `scrape_to_rdf.py` scrapes the website and generates RDF data. `rdf_to_rss.py` converts the RDF data to RSS XML.
3. **Workflow:** The GitHub Action workflow is defined in `.github/workflows/scrape_and_convert.yml`, which triggers on push to the main branch or manual dispatch.

This setup allows you to input the website URL and the paths for RDF and RSS output files when triggering the GitHub Action, which will then perform the scraping, RDF generation, and RSS conversion tasks automatically.
